// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using CitiesTableApp.Models;
using Foundation;
using UIKit;

namespace CitiesTableApp
{
    public partial class CitiesTVController : UITableViewController
    {
        #region Class Variables

        UIRefreshControl refreshControl;
        Dictionary<string, List<string>> cities;
        UITableViewCell reusableSimpleCell;

        #endregion

        public CitiesTVController(IntPtr handle) : base(handle)
        {
        }

        #region Controller Life Cycle
        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            InitializeComponents();
        }
        #endregion
        #region User Interactions
        void RefreshControl_ValueChanged(object sneder, EventArgs e)
        {
            CitiesManager.SharedInstance.FetchCities();
        }
        #endregion

        #region TableView Data Source
        [Export("numberOfSectionsInTableView:")]
        public override nint NumberOfSections(UITableView tableView)
        {
            return cities.Keys.Count;
        }

		public override nint RowsInSection(UITableView tableView, nint section)
		{
            return cities.Keys.Count;
		}
		public override UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
		{
            List<string> lst = new List<string>(cities.Keys);
            var cell = new UITableViewCell(UITableViewCellStyle.Default, "BaseTableViewCell");
            cell.TextLabel.Text = lst[indexPath.Row];
            return cell;
		}


        #endregion

        #region Cities Manager Evemts

        private void SharedInstance_CitiesFetched(object sender, CitiesManager.CitiesEventArgs e)
        {
            cities = e.Cities;
            InvokeOnMainThread(() => refreshControl.EndRefreshing());
        }

        void SharedInstance_CitiesFetchedFailed(object sender, EventArgs e)
        {
            Console.WriteLine("algo fallo...");
        }

        #endregion 

        #region Internal Functionality

        void InitializeComponents(){

            reusableSimpleCell = new UITableViewCell(UITableViewCellStyle.Default, "reusableSimpleCell");

            CitiesManager.SharedInstance.CitiesFetched += SharedInstance_CitiesFetched;
            CitiesManager.SharedInstance.CitiesFetchedFailed += SharedInstance_CitiesFetchedFailed;
            cities = CitiesManager.SharedInstance.GetDefaultCities();
            refreshControl = new UIRefreshControl();
            refreshControl.ValueChanged += RefreshControl_ValueChanged;
            TableView.RefreshControl = refreshControl;
        }

        #endregion
    }
}
